### ISSUE TITLE
Displaying incorrect favorite paths for me

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#113]
The dashboard at https://ondemand.osc.edu for account `jnicklas` is displaying incorrect favorite paths:

![image](https://cloud.githubusercontent.com/assets/4260509/21852345/bce29534-d7e0-11e6-9097-b1035d7a0479.png)

This is in regards to the `/fs/scratch/` appearing.

**Comment by nickjer** [comment]
This returns an empty array for me:

https://github.com/OSC/ood-dashboard/blob/420eb28575cbb3ab5337e7fbcca66d251d2a7af1/config/initializers/ood.rb.osc#L6

as I have no groups that start with the letter `P`.

**Comment by ericfranz** [comment]
Fixed by 402dc8589303af56abe518315a868fcb94f06e38

**Comment by nickjer** [comment]
This is happening again.

![image](https://cloud.githubusercontent.com/assets/4260509/22481721/3e794df2-e7c4-11e6-92fa-1678ff48b766.png)

That is from https://ondemand3-dev.hpc.osc.edu

**Comment by nickjer** [comment]
Updated the dashboard on ondemand3-dev.hpc.osc.edu and it still appears.

**Comment by nickjer** [comment]
Needed to copy over the new initializer for `osc`.
